# Generated by Django 3.2.6 on 2021-08-21 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
        ('shopcart', '0002_auto_20210821_1128'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopcartitem',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='order.order'),
        ),
    ]
