# Generated by Django 3.2.6 on 2021-08-21 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopcart', '0003_shopcartitem_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopcartitem',
            name='shop_cart',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='shopcart.shopcart'),
        ),
    ]
